version: "3"

services:
  website-dev:
    image: website-image
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file:
      - ".env.production"
    ports:
      - "11000:3000"
    restart: unless-stopped