
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./theme-provider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Crm Niventra Capital Advisory India Pvt.Ltd.",
  description: "Generated by Crm Niventra Capital Advisory India Pvt.Ltd.",
  icons: {
    icon: "https://niventracapitaladvisory.com/favicon/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased overflow-x-hidden`}
    >
      <body className="min-h-full flex flex-col bg-white dark:bg-gray-900 overflow-x-hidden w-full max-w-full">
        <ThemeProvider>
          {children}
          <Toaster position="top-right" toastOptions={{ className: "dark:bg-zinc-800 dark:text-white" }} />
        </ThemeProvider>
      </body>
    </html>
  );
}
